
get http://localhost:3001/persons

###
DELETE http://localhost:3001/persons/8

###
post http://localhost:3001/persons
Content-Type: application/json

{
  "name": "你才是恶魔",
  "number": "2222222",
  "id": 8
}

###
PUT http://localhost:3001/persons/8
Content-Type: application/json

{
  "name": "你才是恶魔",
  "number": "3333333",
  "id": 8
}