
get https://phonebook-app-p3.herokuapp.com/api/persons

###
DELETE http://localhost:3001/persons/8

###
post https://phonebook-app-p3.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "你才是恶魔",
  "number": "2222222",
  "id": 5
}

###
PUT https://phonebook-app-p3.herokuapp.com/api/persons/8
Content-Type: application/json

{
  "name": "你才是恶魔",
  "number": "3333333",
  "id": 8
}